import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
await p.goto("http://localhost:8923/index.html", { waitUntil: "networkidle" });
await p.waitForTimeout(800);
await p.click('.nav-item:has-text("商机管理")');
await p.waitForTimeout(500);
await p.screenshot({ path: "D:/HaLeMa/Documents/媒电通工作台/code/meidiantong-workbench/ui-design-runs/深度提炼媒电通工作台AP-20260925-105929-4c9f/shots/v5_dev.png", fullPage: false });
await b.close();
console.log("done");
